### ISSUE TITLE
Support For Custom Mapping

### ISSUE THREAD

**Issue by lurldgbodex** [lurldgbodex/file-parser-library#11]
**Description**
Allow developers to define custom mappings for complex structures.

**Tasks**
- [ ] Implement a mechanism to define custom field mappings (e.g., via annotations).
- [ ] Create a mapping configuration class to hold mapping information.
- [ ] Write unit tests to verify custom mapping functionality.
