### ISSUE TITLE
Document Parsing API

### ISSUE THREAD

**Issue by lurldgbodex** [lurldgbodex/file-parser-library#13]
**Description**
Write documentation for the parsing API.

**Tasks**
- [ ] Update the README.md to include parsing usage examples.
- [ ] Create documentation for each parser class and its methods.
- [ ] Ensure that Javadoc comments are included in the codebase.
