### ISSUE TITLE
Implement XML Parser

### ISSUE THREAD

**Issue by lurldgbodex** [lurldgbodex/file-parser-library#8]
**Description**
Develop a parser for XML files that reads data and maps it to Java objects.

**Tasks**
- [ ] Create an XmlParser class with methods to read XML files.
- [ ] Implement logic to handle nested elements and attributes.
- [ ] Create a method to map parsed XML data to specified Java POJOs.
- [ ] Write unit tests for the XML parsing functionality.
